### ISSUE TITLE
Variable non déclarée dans GTFS2Postgis.php

### ISSUE THREAD

**Issue by loicbcn** [DoFabien/GTFS2Postgis#1]
Line 41 -> if (file_exists($current_file)){ ....

$current_file n'a pas encore été déclarée :/

if (file_exists("_GTFS_EXTRACT/" .$file_str)) fonctionnerait mieux

**Comment by DoFabien** [comment]
Merci,
Je n'ai pas testé mais ça devrait mieux fonctionner en effet !
